repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.10
    hooks:
      # Run the linter.
      - id: ruff-check

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        args: [--config-file=pyproject.toml]
        additional_dependencies: ["pytest", "attrs", "types-attrs", "streamlit", "pandas", "plotly"]
