name: Conversation Simulator CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint-typecheck-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: "3.12.6"
        cache: 'pip'
    
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: "2.0.1"
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
    
    - name: Install dependencies
      run: |
        cd agentune_simulate
        poetry install --sync --no-interaction
    
    - name: Run ruff
      run: |
        cd agentune_simulate
        poetry run ruff check .

    - name: Run mypy
      run: |
        cd agentune_simulate
        poetry run mypy .

    - name: Run tests
      run: |
        cd agentune_simulate
        poetry run python -m pytest
